Only check for h5perf_serial when doing native builds with tests
conda-forge/hdf5-feedstock pull request #149
Opened 2021-01-02 20:11 UTC by erykoff

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2021-01-02 20:11 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-01-02 20:48 UTC, beckermr commented
@conda-forge-admin rerender

2021-01-08 17:54 UTC, scopatz commented on recipe/meta.yaml
> +        {% if build_platform == target_platform %}
Is target_platform documented yet?

2021-01-08 17:55 UTC, scopatz requested changes
target_platform

2021-01-08 20:09 UTC, merged